use ark_ed25519::Fr as ScalarField;

/// Serializes a `ScalarField` secret into a `ScalarField` nonce by concatenating the serialized
/// `secret` to randomly generated bytes of length 32.
/// Inputs:
///     - secret, a Scalar.
///
///Outputs:
///     - nonce, a Scalar.
///
///def nonce_generate(secret):
///  random_bytes = random_bytes(32)
///  secret_enc = G.SerializeScalar(secret)
///  return H3(random_bytes || secret_enc)
fn nonce_generate(_secret: ScalarField) -> ScalarField {
    unimplemented!();
}
